### PR TITLE
issue20 : Fused the game of life algo into the gui. look in kivy_app

### PR DESCRIPTION
**Pull request by fabrice-eberle**
check issue 20 for further description

### CODE REVIEW

**Comment by fabrice-eberle** [comment]
@juldimag @sekkurocode @Sara25s @redibaj

**Comment by Sara25s** [comment]
Hey Team,

I hope everything is going smoothly for you! I wanted to inform you about some significant updates in the Game of Life project.
I made extensive changes in the game_of_life.py file to integrate exciting new features. To ensure smooth functionality, I had to make corresponding adjustments in the kivy_app.py file.
From now on, please use the main.py file to run the application. This file serves as a central entry point and connects both game_of_life.py and kivy_app.py.
If you encounter any issues or have questions about these changes, feel free to open an issue or reach out to me directly. BG @Sara25s 
@juldimag @sekkurocode @redibaj @fabrice-eberle

**Comment by fabrice-eberle** [comment]
@sekkurocode mmmh I see thats weird, my local version works. Maybe I made a wrong push or I was on a wrong branch. I will update

**Comment by fabrice-eberle** [comment]
Oh yes it seems to be missing all of the code I implemented.

**Pull request closed without merging**
